export const ROUTES = {
  AUTH: {
    LOGIN: 'Login',
    REGISTER: 'Register',
    FORGOT_PASSWORD: 'ForgotPassword',
  },

  MAIN: {
    HOME: 'Home',
    EMPLOYEES: 'Employees',
    CREATE_EMPLOYEE: 'CreateEmployee',
    EMPLOYEE_DETAIL: 'EmployeeDetail',
    EDIT_EMPLOYEE: 'EditEmployee',
    ACCOUNTS: 'Accounts',
    ACCOUNT_DETAIL: 'AccountDetail',
    DEPARTMENTS: 'Departments',
    CREATE_DEPARTMENT: 'CreateDepartment',
    DEPARTMENT_DETAIL: 'DepartmentDetail',
    EDIT_DEPARTMENT: 'EditDepartment',
    TEAMS: 'Teams',
    CREATE_TEAM: 'CreateTeam',
    TEAM_DETAIL: 'TeamDetail',
    EDIT_TEAM: 'EditTeam',
    PERMISSIONS: 'Permissions',
    CREATE_PERMISSION: 'CreatePermission',
    PERMISSION_DETAIL: 'PermissionDetail',
    EDIT_PERMISSION: 'EditPermission',
    ROLE_PERMISSIONS: 'RolePermissions',
    CREATE_ROLE_PERMISSION: 'CreateRolePermission',
    ROLE_PERMISSION_DETAIL: 'RolePermissionDetail',
    EDIT_ROLE_PERMISSION: 'EditRolePermission',
    ACLS: 'Acls',
    CREATE_ACL: 'CreateAcl',
    ACL_DETAIL: 'AclDetail',
    EDIT_ACL: 'EditAcl',
    CREATE_DOCUMENT: 'CreateDocument',
    EDIT_DOCUMENT: 'EditDocument',
    DOCUMENT_DETAIL: 'DocumentDetail',
    MY_SUBMISSIONS: 'MySubmissions',
    PENDING_APPROVALS: 'PendingApprovals',
    PUBLISHED_DOCUMENTS: 'PublishedDocuments',
    WORKFLOW_DETAIL: 'WorkflowDetail',
    CHANGE_PASSWORD: 'ChangePassword',
  },
};
